sudo: required
services:
  - docker

before_install:
  - docker build -t solareenlo/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true solareenlo/react-test npm run test -- --watchAll=falseb

after_success:
  - docker build -t solareenlo/multi-client ./client
  - docker build -t solareenlo/multi-nginx ./nginx
  - docker build -t solareenlo/multi-server ./server
  - docker build -t solareenlo/multi-worker ./worker
  # Docker CLIにログインする
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  # 作ったイメージをDocker Hubにpushする
  - docker push solareenlo/multi-client
  - docker push solareenlo/multi-nginx
  - docker push solareenlo/multi-server
  - docker push solareenlo/multi-worker
